// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duebejkrrvuodwbforkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZWJlamtycnZ1b2R3YmZvcmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Nzk0NjAsImV4cCI6MjA2NjM1NTQ2MH0.-RgHNXqOFtfvWEubU2TGVoAoAl3CRm_emxnNhgOjl0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);